{{- if eq (include "coordimap.serviceAccountCreate" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coordimap.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coordimap.labels" . | nindent 4 }}
  {{- if and (not (kindIs "string" .Values.serviceAccount)) .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
